server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # 1. จัดการ History API ของ Vue Router (ไม่ให้กด Refresh แล้วขึ้น 404)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. ส่งต่อคำขอ API ไปยังคอนเทนเนอร์ NestJS Backend ใน Docker
    # 🌟 เติม ^~ ตรงนี้! เพื่อสั่งให้ Nginx หยุดจับคู่กับกฎ .css/.js ด้านล่าง
    location ^~ /api/ {
        proxy_pass http://backend:5000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_cache_bypass $http_upgrade;
    }

    # 2.1 ส่งต่อ WebSocket (Socket.io) ไปยังคอนเทนเนอร์ NestJS Backend
    location ^~ /socket.io/ {
        proxy_pass http://backend:5000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # 3. ทำ Cache สำหรับไฟล์รูปภาพและ Static Assets (ใช้เฉพาะของฝั่ง Frontend Vue.js)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|webp)$ {
        expires 6M; # ให้เบราว์เซอร์จำไฟล์เหล่านี้ไว้ 6 เดือน
        access_log off; # ปิดการเก็บ Log ของไฟล์รูปภาพเพื่อลดขนาดไฟล์ Log
        add_header Cache-Control "public, max-age=15552000, immutable";
    }

    # 4. จัดการ Error Page
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}