name: Auto Deploy Tum Krok Zing

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into OCI Server and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/AN-END-TO-END-ONLINE-FOOD-ORDERING-SYSTEM-A-CASE-STUDY-OF-TUM-KROK-ZING-RESTAURANT
          
          # ดึงโค้ดล่าสุดให้ตรงกับ GitHub 100%
          git fetch origin main
          git reset --hard origin/main
          
          # รัน Docker ที่โฟลเดอร์หลักสุดเลย (ลบ cd backend ออกแล้ว)
          sudo docker-compose up -d --build

          # รอให้ Database และ Backend พร้อมทำงาน
          sleep 8

          # ซิงค์โครงสร้างตารางฐานข้อมูลและใส่ข้อมูลสูตรอาหารลงในเซิร์ฟเวอร์จริง
          sudo docker-compose exec -T backend npx prisma db push --accept-data-loss
          sudo docker-compose exec -T backend npx prisma db seed

          # รีสตาร์ท Backend เพื่อโหลดสูตรและคลังวัตถุดิบใหม่เข้าสู่ระบบ
          sudo docker-compose restart backend
